### ISSUE TITLE
ERROR Contamination failed

### ISSUE THREAD

**Issue by SarahL98** [genepi/haplocheck#21]
Hi! I tried running haplocheck on some VCF files. If works on the sample NA12878 which has about 3000+ coverage in the VCF (in the HTML file it said 2400 coverage) for the SNPs but for another sample which has around 1700x get an error. Both samples are run using the same pipeline and haplocheck command. I get this error:

haplocheck 1.3.2
https://github.com/genepi/haplocheck
(c) 2020 Sebastian Schoenherr, Hansi Weissensteiner, Lukas Forer

Check for Contamination..
RUN Load file...
java.lang.NumberFormatException: For input string: "."
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
        at java.base/java.lang.Double.valueOf(Double.java:506)
        at importer.VcfImporter.load(VcfImporter.java:202)
        at genepi.haplocheck.steps.ContaminationStep.detectContamination(ContaminationStep.java:67)
        at genepi.haplocheck.steps.ContaminationStep.run(ContaminationStep.java:36)
        at genepi.haplocheck.commands.ContaminationCommand.call(ContaminationCommand.java:55)
        at genepi.haplocheck.commands.ContaminationCommand.call(ContaminationCommand.java:1)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at genepi.haplocheck.App.main(App.java:32)
ERROR Contamination failed

Thank you in advance! :)

**Comment by seppinho** [comment]
Can you share a test file with me?
Best
